version: '3.9'

services:
  cassandra_init:
    image: cassandra:4
    ports:
      - 9042:9042
    volumes:
      - /var/lib/cassandra

  cassandra_instagram:
    image: cassandra:4
    depends_on:
      - cassandra_init
    container_name: cassandra_instagram
    volumes:
      - ./cassandra_init.sh:/cassandra_init.sh
    entrypoint: ["/cassandra_init.sh"]
    restart: "no"

  postgres_instagram:
    image: postgres:15
    container_name: postgres_instagram
    command: 
      - -p 5432
    expose: 
      - 5432
    env_file:
      - .env-non-dev


  fastapi_instagram_app:
    container_name: fastapi_instagram
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - cassandra_instagram
      - postgres_instagram
    env_file: 
      - .env-non-dev
    command: ["/fastapi_app/wait_for_cassandra.sh", "-t", "30", "cassandra_instagram:9042", "--", "/fastapi_app/start.sh"]
