version: '3.9'

services:
  cassandra_instagram:
    image: cassandra:latest
    container_name: cassandra_instagram
    ports:
      - 9042:9042
    environment:
     - CASSANDRA_CLUSTER_NAME=cloudinfra
    volumes:
      - ./cassandra_init.sh:/cassandra_init.sh
      - /var/lib/cassandra
    entrypoint: ["/cassandra_init.sh"]
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5

  postgres_instagram:
    image: postgres:15
    container_name: postgres_instagram
    command: -p 5432
    expose: 
      - 5432
    env_file:
      - .env

  fastapi_instagram_app:
    container_name: fastapi_instagram
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - cassandra_instagram
      - postgres_instagram
    env_file:
      - .env

