version: '3.9'

services:
  cassandra_instagram:
    image: cassandra:4
    container_name: cassandra_instagram
    build:
      context: ./docker_cassandra
      dockerfile: Dockerfile

  postgres_instagram:
    image: postgres:15
    container_name: postgres_instagram
    command: 
      - -p 5432
    expose: 
      - 5432
    env_file:
      - .env-non-dev


  fastapi_instagram_app:
    container_name: fastapi_instagram
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres_instagram
      - cassandra_instagram
    env_file: 
      - .env-non-dev
    command: ["/fastapi_app/wait_for_cassandra.sh", "-t", "150", "cassandra_instagram:9042", "--", "/fastapi_app/start.sh"]
    restart: on-failure
