"""empty message

Revision ID: 0915ea5f0c5a
Revises: 4f4ff9f33ef0
Create Date: 2024-04-06 15:16:56.276071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0915ea5f0c5a'
down_revision: Union[str, None] = '4f4ff9f33ef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
