"""Fiw

Revision ID: fbdaef2d7cdb
Revises: deeea2ba41d6
Create Date: 2024-01-24 18:50:15.705460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbdaef2d7cdb'
down_revision: Union[str, None] = 'deeea2ba41d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_image_id'), 'image', ['id'], unique=False)
    op.drop_column('image', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_image_id'), table_name='image')
    # ### end Alembic commands ###
